Fixed empty line number issue
socketsupply/union-app-studio pull request #21
Opened 2018-01-24 14:05 UTC by sunilhari

#11 Empty console.log() prints line number.

Omitted the lines from `result` array which only have line numbers.

2018-01-24 15:50 UTC, sallar commented
@sunilhari your editor has re-formatted this file and changed the indention to 4. I think you need to revert the file and do your change again.

2018-01-24 17:13 UTC, 0x00A commented on src/node_modules/editor/index.js
> +    }
LGTM! 👍

2018-01-24 17:14 UTC, heapwolf requested changes
As @sallar pointed out, your editor has made a lot of whitespace changes. Other than that, the actual fix looks good.

2018-01-25 11:33 UTC, sunilhari commented
will do it right away.

2018-01-25 11:47 UTC, sunilhari commented
Have changed the indentation.Actually have kept indentation as it as and added the fix like @sallar  suggested.

But not sure how it got merge conflict.When i have submitted PR it had no conflicts.

2018-01-25 17:04 UTC, sunilhari commented
Will raise a new pull request incorporating changes.

2018-01-25 17:04 UTC, closed without merging